server:
  port: 8102
spring:
  application:
    name: market-data-csv-uploader
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
api-gateway-url: ${API_GATEWAY_URL:http://localhost:8080}